### ISSUE TITLE
feat: Multiple active projects

### ISSUE THREAD

**Issue by vrokolos** [gioboa/jira-plugin#119]
Can we have a setting in config to active multiple active projects at once? I've got a project with multiple subfolders each a different jira project.

**Comment by gioboa** [comment]
Hi @vrokolos all the plugin feature are straight to one project.
Use one or more project at once maybe should be possible, I need to think how implement the feature? :smile: :+1:

**Comment by bittner** [comment]
We don't have the notion of a "current project". We're a DevOps company and we have a lot of customers that we all support from a single backlog by squad (team). On our (team) Kanban board we have tickets from all projects (i.e. Jira namespaces, which represent customers).

It would make sense for us to allow listing all tickets of a (Kanban) board, e.g. filtered by statuses (e.g. "show all tickets from board 'Foo Bar' where status not in [ Backlog, Done ]").

Not sure if you have ever envisioned such a use case. :worried:

**Comment by gioboa** [comment]
Hi, so you meen that your Kanban board isn't under a specific project?
If you search for a specific task which JQL you use? Can you send me an example?

**Comment by anothertobi** [comment]
Hi @gioboa 

I am working together with @bittner.

We use our Kanban board as an aggregator for multiple projects.

A simple JQL query could look like `Squad = Capella AND resolution = Unresolved ORDER BY Rank ASC`. This will search over all projects in Jira (due to the lack of `project =`) for issues "assigned" to a squad (team). We implemented the `Squad` field as a custom field in Jira.

Sometimes we also search using other filters (e.g. `filter = "Projects Capella" AND ...`)

I hope this helps y'all 🙈

**Comment by soufianebenali** [comment]
Hi @gioboa,

I'm @bittner's colleague this is an example of JQL query in Jira that we are using:
`(squad = "Beta Team" OR labels in ("Beta Team")) AND project not in ("Project A", "Project B")`

`squad` is a custom field that we are using in all our issues to assign a ticket to a specific Team.

How you see the filter doesn't have any reference to a specific project.

We saved this query as a filter and we created and configured the kanban board to use the saved filter.

Saluti

**Comment by gioboa** [comment]
Thanks for your feedback. I will check the possibility to implement logic without current project or with multiple projects.

**Comment by gioboa** [comment]
I though a bit and we can implement a "wildcard" project.
In current project we can select it and the plugin will search in all projects except the hide projects you can define in configuration. What do you think?

**Comment by bittner** [comment]
Anyone using Jira would probably define their workflow as "product centric" (project / customer / product / component) or "support centric" (generic view across several or all projects). But isn't "project" just an *arbitrary* filter? Maybe it's a common one, but it's totally arbitrary, isn't it?

How I understand the plugin is:

* From the **status bar** I select a "filtering" (not a Jira *filter*, a generic JQL query currently hardcoded on project)
* From the **explorer menu** I select the "group by" for the widget.

Wouldn't it make sense to use generic JQL for the filtering? Since "project" seems to be a popular starting point for filtering this could be proposed by default when we create a new filtering. Hence, this could be a "PROJECT in ..." by default, but editable and replaceable by some other valid JQL.

Shouldn't we simply have a set of predefined JQL queries that can be easily edited? Without focusing too much on "a project"? (Where are those queries stored by the way? I have a hard time spotting it in the code.)

**Comment by gioboa** [comment]
You can find all the used JQL in the project readme. [Here](https://github.com/gioboa/jira-plugin#filters) My first idea was to create a Jira viewer and select a specific project it's a constraint in all the logic. Add the ability to define custom JQL I think it can be possible.

**Comment by gioboa** [comment]
With current code there is the possibility to define a custom JQL, but the results are filtered by project. :expressionless:

**Comment by vrokolos** [comment]
Just please add a parameter in settings and disable this single line: 

https://github.com/gioboa/jira-plugin/blob/3a0ba8f4cfec54dbcaf7ea21fdd6eae80b058466/src/services/select-values.service.ts#L197
