### ISSUE TITLE
Can't authenticate with Google Jira sign in

### ISSUE THREAD

**Issue by WiggyBennett** [gioboa/jira-plugin#185]
My company's Jira account uses Google to sign in. When I try to authenticate in the plug in nothing happens. It appears to complete the authentication but no projects are available to select. If I repeat the setup process and type my password deliberately incorrectly, the same thing happens. 
Any help would be appreciated.

**Comment by gioboa** [comment]
Hi @WiggyBennett 

The best way to solve the problem is debug the plugin in your environment.

- clone the repo
- install deps
- press F5 From VsCode (first instance)
- another instance of VsCode will be launched (second instance)
- debug the second instance by the first one, breakpoints are available

eg.
<img width="1680" alt="Screenshot 2023-03-02 at 18 52 31" src="https://user-images.githubusercontent.com/35845425/222511709-5d4246f5-7d6a-410d-ad2c-6df93cdfd8e9.png">
